music/urls.py
from django.urls import path
from.import views

app_name = 'music'

urlpatterns = [
    #/music/
    path('', views.IndexView.as_view(), name='index'),
    #/music/register/
    path('register/', views.UserFormView.as_view(), name = 'register'),
    #/music/album_id/
    path('<int:pk>/', views.DetailView.as_view(), name="detail"),
    #/music/album/add/
    path('album/add/', views.AlbumCreate.as_view(), name = 'album-add'),
    #/music/album/2/
    path('album/<int:pk>/', views.AlbumUpdate.as_view(), name = 'album-update'),
    #music/album/2/delete/
    path('album/<int:pk>/delete/', views.AlbumDelete.as_view(), name = 'album-delete'),



]

website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls', namespace='music')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.urls import reverse

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk' : self.pk})


    def __str__(self):
        return self.artist + ' - '+ self.album_title

class Song(models.Model):
     album=models.ForeignKey(Album, on_delete=models.CASCADE)
     file_type = models.CharField(max_length=10)
     song_title = models.CharField(max_length=250)
     audio_track = models.FileField()


     def __str__(self):
         return self.song_title +"- " + self.file_type

music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)



    class Meta:
        model = User
        fields = ['username', 'email', 'password']

#All this stuff is blue print of our form

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView #used for edit the objects
from .models import Album
from django.urls import reverse_lazy#used for DeleteAlbum function
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login# these are used to match the username and password to the database
from  django.views.generic import View
from .forms import UserForm# it imports the class in forms.py
from .models import Song
from django.shortcuts import render_to_response

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_album' #used because we can not take object_list name

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model = Album       #used because django need to know what kind of thing you create
    fields = ['artist', 'album_title', 'genre', 'album_logo']    #Attributes which you gona work

class AlbumUpdate(UpdateView):
    model = Album
    fields =  ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index',)

class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    #display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form':form})

    #process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user =  form.save(commit=False)

            #cleaned (normilised) data
            username =  form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password) # We used this because password is not a simple text it is hash value so we need to convert it in string by this.
            user.save()

            #returns Usesr objects if credentials are correct
            user = authenticate(username=username , password=password  )

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('music:index')
        return render(request, self.template_name,{'form':form})

music/templates/music/album_form.html
{% extends 'music/basic.html' %}

{% block title %}Add a New Album {% endblock %}
{% block album_active %} active {% endblock %}

{% block html %}
    <div class="container-fluid" >\
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">

                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data"> <!-- enctype is used to save data-->                            {% csrf_token %}
                            {%  include 'music/form-template.html' %}
                            <div class="from-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

music/templates/music/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Pagal World{% endblock %}</title>
    {% load staticfiles %}
<link type="text/css" rel="stylesheet" href="{% static 'music/style.css' %}">
<link rel="stylesheet" href="{% static 'music/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
 <nav class="navbar navbar-default navbar-fixed-top first">
            <div class="container">
                <div class="row">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                          <i class="fa fa-bars"></i>
                        </button>
                        <div class="logo-wrapper">
                            <a class="navbar-brand" href="{% url 'music:index' %}" style="word-spacing: 3em;">
                               <span>PagalWorld</span>
                                <span> <i class="fa fa-music" aria-hidden="true" style="position:absolute; margin-left:-25px;" ></i>Albums</span>
                                <span><i class="fa fa-play" aria-hidden="true" style="position: absolute; margin-left:-25px "></i>Songs</span>
                            </a>
                            <form class="search-button" role="search" method="get" action="#">
                                <div class="form-group">
                                    <input type="text"  name="q" value="" style="border-radius:5%; height: 33px; border: 1px solid gray;">
                                      <button type="submit" class="btn btn-default ">Search</button>
                                </div>
                        </form>
                            <ul class="navbar-brand" style="list-style: none; " >
                                <li>
                                    <a href="{% url 'music:album-add' %}" style="text-decoration: none;">
                                        <i class="fa fa-plus" aria-hidden="true"></i>
                                        <span style="text-decoration: none;">Add Album</span>
                                    </a>
                                    <a href="" style="text-decoration: none;">

                                        <span style="text-decoration: none;margin-left: 25px"><i class="fa fa-user-plus" aria-hidden="true"></i>Logout</span>
                                    </a>
                                    <a href="{% url 'music:register' %}" style="text-decoration: none;">
                                        <span style="padding-left: 35px;"><i class="fa fa-registered" aria-hidden="true"></i>Register</span>
                                    </a>
                                </li>

                            </ul>
                        </div>
                        </div>
                    </div>
                </div>

            </div>
        </nav>

{% block html %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/basic.html' %}
{% block title %}Album Detail{% endblock %}
{% block html %}
    <div class="box" style="padding-top: 161px;">
        <img src="{{ album.album_logo.url }}" style="height: 250px">

        <h1>{{ album.album_title }}</h1>
        <h2>{{ album.artist }}</h2>

        <ul>
            {% for song in album.song_set.all %}
                <li>{{ song.song_title }}-{{ song.file_type }}</li>
            {% endfor %}
        </ul>

        {% if error_message %}
            <p><b>{{ error_message }}</b></p>
        {% endif %}

        <form action="{% url 'music:detail' album.id %}" method="post">
            {% csrf_token %}
            {% for song in album.song_set.all %}
                <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
                <label for="song{{ forloop.counter }}">
                    {{ song.song_title }}
                    {% if song.is_favorite %}
                        <img src="http://i.imgur.com/b9b13Rd.png"/>
                    {% endif %}
                <p><audio controls="controls">
                    <source src="{{ song.audio_track.url }}" type="audio/mpeg"/>
                </audio> </p>
                </label><br>
             {% endfor %}

            <input type="submit" value="favorite">
        </form>
    </div>
{% endblock %}

music/templates/music/form-template.html
 <div class="box" style="padding-top: 155px;">
    {% for x in form%}
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ x.errors }}</span>
        </div>

        <label class="control-lable col-sm-2">{{ x.label_tag }}</label> <!--pta nahi label_tag q liya h-->
        <div class="col-sm-10">{{x}}</div>
    {% endfor %}
</div>

music/templates/music/index.html
{% extends 'music/basic.html' %}
{% block title %}Rajput{% endblock %}
{% block html %}
     <div class="box" style="padding-top: 150px;">
        {% if all_album %}
            <ul>
                 <h1>Here all my albums</h1>
                {% for x in all_album %}
                    <li><a href="/music/{{ x.id }}">{{ x.album_title }}</a></li>
                    <!--DELETE-->
                    <form action="{% url 'music:album-delete' x.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name = "album_id" value="{{ album.id }}">
                        <button type="submit" class="btn btn-default btn-sm">
                            <i class="fa fa-trash" aria-hidden="true"></i>
                        </button>
                    </form>
                     <!--ALBUM LOGO-->
                    <a href="{% url 'music:detail' x.id %}">
                        <img src="{{ x.album_logo.url }}" class="img-responsive" style="height: 250px;"> <!--url is used because we need the path of image store in databse-->
                    </a>
                {% endfor %}
            </ul>
        {% else %}
            <h3>you don't have any album</h3>
        {% endif %}
     </div>
{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/basic.html' %}

{% block title %}Register {% endblock %}


{% block html %}
    <div class="container-fluid" >
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Create A New Account</h3>
                        {% if error_message %}
                            <p><s>{{ error_message }}</s></p>
                        {% endif %}

                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data"> <!-- enctype is used to save data-->                            {% csrf_token %}
                            {%  include 'music/form-template.html' %}
                            <div class="from-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}